name: Deploy

on: ['deployment']

jobs:
  deployment:

    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v1
    - name: 'use node 8.x'
      uses: actions/setup-node@v1
      with:
        node-version: 8.x

    - name: 'deployment pending'
      uses: 'deliverybot/deployment-status@master'
      with:
        state: 'pending'
        token: '${{ github.token }}'

    - name: 'deploy'
      env:
        PRODUCTION_SA: '${{ secrets.PRODUCTION_SA }}'
        DEVELOPMENT_SA: '${{ secrets.DEVELOPMENT_SA }}'
      run: |
        npm install
        echo 'deploy with ${{ github.event.deployment.environment }}_sa'
        echo $PRODUCTION_SA > production-sa.json
        echo $DEVELOPMENT_SA > development-sa.json
        cp ${{ github.event.deployment.environment }}-sa.json service-account.json
        echo ''
        echo ''
        echo ''
        echo "${{ github.event.deployment.environment }}-sa.json"
        cat ${{ github.event.deployment.environment }}-sa.json
        GOOGLE_APPLICATION_CREDENTIALS=./service-account.json make deploy/${{ github.event.deployment.environment }}

    - name: 'deployment success'
      if: success()
      uses: 'deliverybot/deployment-status@master'
      with:
        state: 'success'
        token: '${{ github.token }}'

    - name: 'deployment failure'
      if: failure()
      uses: 'deliverybot/deployment-status@master'
      with:
        state: 'failure'
        token: '${{ github.token }}'
